/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TentsRouteImport } from './routes/tents'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FootwearRouteImport } from './routes/footwear'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CarriersRouteImport } from './routes/carriers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApparelRouteImport } from './routes/apparel'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as AkunIndexRouteImport } from './routes/akun.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as EnSplatRouteImport } from './routes/en/$'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AkunProfileRouteImport } from './routes/akun.profile'
import { Route as AkunOrdersRouteImport } from './routes/akun.orders'
import { Route as AkunAddressesRouteImport } from './routes/akun.addresses'
import { Route as AdminVouchersRouteImport } from './routes/admin/vouchers'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminSizeGuidesRouteImport } from './routes/admin/size-guides'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminRestocksRouteImport } from './routes/admin/restocks'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLanguagesRouteImport } from './routes/admin/languages'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminGlossaryRouteImport } from './routes/admin/glossary'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminDesignRouteImport } from './routes/admin/design'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAttributesRouteImport } from './routes/admin/attributes'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as LangStoresRouteImport } from './routes/$lang.stores'
import { Route as LangPrivacyRouteImport } from './routes/$lang.privacy'
import { Route as LangPermintaanRouteImport } from './routes/$lang.permintaan'
import { Route as LangInquiryRouteImport } from './routes/$lang.inquiry'
import { Route as LangCheckoutRouteImport } from './routes/$lang.checkout'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products.index'
import { Route as LangPermintaanIndexRouteImport } from './routes/$lang.permintaan.index'
import { Route as LangInquiryIndexRouteImport } from './routes/$lang.inquiry.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AdminSettingsPrivacyRouteImport } from './routes/admin/settings.privacy'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings.notifications'
import { Route as AdminReportsRegionalRouteImport } from './routes/admin/reports.regional'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products.new'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders.$id'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin/inquiries.$id'
import { Route as AdminCustomersEmailRouteImport } from './routes/admin/customers.$email'
import { Route as LangProdukSlugRouteImport } from './routes/$lang.produk.$slug'
import { Route as LangProductsSlugRouteImport } from './routes/$lang.products.$slug'
import { Route as LangPermintaanTerkirimRouteImport } from './routes/$lang.permintaan.terkirim'
import { Route as LangOrderIdRouteImport } from './routes/$lang.order.$id'
import { Route as LangInquirySentRouteImport } from './routes/$lang.inquiry.sent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksWeeklyInquirySummaryRouteImport } from './routes/api/public/hooks/weekly-inquiry-summary'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksMidtransRouteImport } from './routes/api/public/hooks/midtrans'
import { Route as AdminStoresIdStockRouteImport } from './routes/admin/stores.$id.stock'
import { Route as AdminProductsIdStockRouteImport } from './routes/admin/products.$id.stock'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products.$id.edit'
import { Route as AdminCustomersEmailExportRouteImport } from './routes/admin/customers.$email.export'
import { Route as AdminCustomersEmailDeleteRouteImport } from './routes/admin/customers.$email.delete'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TentsRoute = TentsRouteImport.update({
  id: '/tents',
  path: '/tents',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FootwearRoute = FootwearRouteImport.update({
  id: '/footwear',
  path: '/footwear',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersRoute = CarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelRoute = ApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunIndexRoute = AkunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AkunRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/en/$',
  path: '/en/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunProfileRoute = AkunProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AkunRoute,
} as any)
const AkunOrdersRoute = AkunOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AkunRoute,
} as any)
const AkunAddressesRoute = AkunAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AkunRoute,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/admin/vouchers',
  path: '/admin/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/admin/stores',
  path: '/admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSizeGuidesRoute = AdminSizeGuidesRouteImport.update({
  id: '/admin/size-guides',
  path: '/admin/size-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/admin/shipping',
  path: '/admin/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestocksRoute = AdminRestocksRouteImport.update({
  id: '/admin/restocks',
  path: '/admin/restocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/admin/languages',
  path: '/admin/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGlossaryRoute = AdminGlossaryRouteImport.update({
  id: '/admin/glossary',
  path: '/admin/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignRoute = AdminDesignRouteImport.update({
  id: '/admin/design',
  path: '/admin/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttributesRoute = AdminAttributesRouteImport.update({
  id: '/admin/attributes',
  path: '/admin/attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LangStoresRoute = LangStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangPermintaanRoute = LangPermintaanRouteImport.update({
  id: '/permintaan',
  path: '/permintaan',
  getParentRoute: () => LangRoute,
} as any)
const LangInquiryRoute = LangInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => LangRoute,
} as any)
const LangCheckoutRoute = LangCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LangRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPermintaanIndexRoute = LangPermintaanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPermintaanRoute,
} as any)
const LangInquiryIndexRoute = LangInquiryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangInquiryRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsPrivacyRoute = AdminSettingsPrivacyRouteImport.update({
  id: '/admin/settings/privacy',
  path: '/admin/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/admin/settings/notifications',
    path: '/admin/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportsRegionalRoute = AdminReportsRegionalRouteImport.update({
  id: '/admin/reports/regional',
  path: '/admin/reports/regional',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInquiriesRoute,
} as any)
const AdminCustomersEmailRoute = AdminCustomersEmailRouteImport.update({
  id: '/$email',
  path: '/$email',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const LangProdukSlugRoute = LangProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsSlugRoute = LangProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangPermintaanTerkirimRoute = LangPermintaanTerkirimRouteImport.update({
  id: '/terkirim',
  path: '/terkirim',
  getParentRoute: () => LangPermintaanRoute,
} as any)
const LangOrderIdRoute = LangOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => LangRoute,
} as any)
const LangInquirySentRoute = LangInquirySentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => LangInquiryRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyInquirySummaryRoute =
  ApiPublicHooksWeeklyInquirySummaryRouteImport.update({
    id: '/api/public/hooks/weekly-inquiry-summary',
    path: '/api/public/hooks/weekly-inquiry-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMidtransRoute = ApiPublicHooksMidtransRouteImport.update({
  id: '/api/public/hooks/midtrans',
  path: '/api/public/hooks/midtrans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresIdStockRoute = AdminStoresIdStockRouteImport.update({
  id: '/$id/stock',
  path: '/$id/stock',
  getParentRoute: () => AdminStoresRoute,
} as any)
const AdminProductsIdStockRoute = AdminProductsIdStockRouteImport.update({
  id: '/admin/products/$id/stock',
  path: '/admin/products/$id/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/admin/products/$id/edit',
  path: '/admin/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersEmailExportRoute =
  AdminCustomersEmailExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AdminCustomersEmailRoute,
  } as any)
const AdminCustomersEmailDeleteRoute =
  AdminCustomersEmailDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AdminCustomersEmailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/accessories': typeof AccessoriesRoute
  '/akun': typeof AkunRouteWithChildren
  '/apparel': typeof ApparelRoute
  '/auth': typeof AuthRoute
  '/carriers': typeof CarriersRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/footwear': typeof FootwearRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/tents': typeof TentsRoute
  '/wishlist': typeof WishlistRoute
  '/$lang/checkout': typeof LangCheckoutRoute
  '/$lang/inquiry': typeof LangInquiryRouteWithChildren
  '/$lang/permintaan': typeof LangPermintaanRouteWithChildren
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/stores': typeof LangStoresRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/design': typeof AdminDesignRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/restocks': typeof AdminRestocksRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/size-guides': typeof AdminSizeGuidesRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/akun/addresses': typeof AkunAddressesRoute
  '/akun/orders': typeof AkunOrdersRoute
  '/akun/profile': typeof AkunProfileRoute
  '/c/$slug': typeof CSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/$': typeof EnSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/akun/': typeof AkunIndexRoute
  '/en/': typeof EnIndexRoute
  '/$lang/inquiry/sent': typeof LangInquirySentRoute
  '/$lang/order/$id': typeof LangOrderIdRoute
  '/$lang/permintaan/terkirim': typeof LangPermintaanTerkirimRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/produk/$slug': typeof LangProdukSlugRoute
  '/admin/customers/$email': typeof AdminCustomersEmailRouteWithChildren
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/reports/regional': typeof AdminReportsRegionalRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/privacy': typeof AdminSettingsPrivacyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$lang/inquiry/': typeof LangInquiryIndexRoute
  '/$lang/permintaan/': typeof LangPermintaanIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/customers/$email/delete': typeof AdminCustomersEmailDeleteRoute
  '/admin/customers/$email/export': typeof AdminCustomersEmailExportRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/products/$id/stock': typeof AdminProductsIdStockRoute
  '/admin/stores/$id/stock': typeof AdminStoresIdStockRoute
  '/api/public/hooks/midtrans': typeof ApiPublicHooksMidtransRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/weekly-inquiry-summary': typeof ApiPublicHooksWeeklyInquirySummaryRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/apparel': typeof ApparelRoute
  '/auth': typeof AuthRoute
  '/carriers': typeof CarriersRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/footwear': typeof FootwearRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/tents': typeof TentsRoute
  '/wishlist': typeof WishlistRoute
  '/$lang/checkout': typeof LangCheckoutRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/stores': typeof LangStoresRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/design': typeof AdminDesignRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/restocks': typeof AdminRestocksRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/size-guides': typeof AdminSizeGuidesRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/akun/addresses': typeof AkunAddressesRoute
  '/akun/orders': typeof AkunOrdersRoute
  '/akun/profile': typeof AkunProfileRoute
  '/c/$slug': typeof CSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/$': typeof EnSplatRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/akun': typeof AkunIndexRoute
  '/en': typeof EnIndexRoute
  '/$lang/inquiry/sent': typeof LangInquirySentRoute
  '/$lang/order/$id': typeof LangOrderIdRoute
  '/$lang/permintaan/terkirim': typeof LangPermintaanTerkirimRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/produk/$slug': typeof LangProdukSlugRoute
  '/admin/customers/$email': typeof AdminCustomersEmailRouteWithChildren
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/reports/regional': typeof AdminReportsRegionalRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/privacy': typeof AdminSettingsPrivacyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$lang/inquiry': typeof LangInquiryIndexRoute
  '/$lang/permintaan': typeof LangPermintaanIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/customers/$email/delete': typeof AdminCustomersEmailDeleteRoute
  '/admin/customers/$email/export': typeof AdminCustomersEmailExportRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/products/$id/stock': typeof AdminProductsIdStockRoute
  '/admin/stores/$id/stock': typeof AdminStoresIdStockRoute
  '/api/public/hooks/midtrans': typeof ApiPublicHooksMidtransRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/weekly-inquiry-summary': typeof ApiPublicHooksWeeklyInquirySummaryRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/accessories': typeof AccessoriesRoute
  '/akun': typeof AkunRouteWithChildren
  '/apparel': typeof ApparelRoute
  '/auth': typeof AuthRoute
  '/carriers': typeof CarriersRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/footwear': typeof FootwearRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/tents': typeof TentsRoute
  '/wishlist': typeof WishlistRoute
  '/$lang/checkout': typeof LangCheckoutRoute
  '/$lang/inquiry': typeof LangInquiryRouteWithChildren
  '/$lang/permintaan': typeof LangPermintaanRouteWithChildren
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/stores': typeof LangStoresRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/design': typeof AdminDesignRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/restocks': typeof AdminRestocksRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/size-guides': typeof AdminSizeGuidesRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/akun/addresses': typeof AkunAddressesRoute
  '/akun/orders': typeof AkunOrdersRoute
  '/akun/profile': typeof AkunProfileRoute
  '/c/$slug': typeof CSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/$': typeof EnSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/akun/': typeof AkunIndexRoute
  '/en/': typeof EnIndexRoute
  '/$lang/inquiry/sent': typeof LangInquirySentRoute
  '/$lang/order/$id': typeof LangOrderIdRoute
  '/$lang/permintaan/terkirim': typeof LangPermintaanTerkirimRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/produk/$slug': typeof LangProdukSlugRoute
  '/admin/customers/$email': typeof AdminCustomersEmailRouteWithChildren
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/reports/regional': typeof AdminReportsRegionalRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/privacy': typeof AdminSettingsPrivacyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$lang/inquiry/': typeof LangInquiryIndexRoute
  '/$lang/permintaan/': typeof LangPermintaanIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/customers/$email/delete': typeof AdminCustomersEmailDeleteRoute
  '/admin/customers/$email/export': typeof AdminCustomersEmailExportRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/products/$id/stock': typeof AdminProductsIdStockRoute
  '/admin/stores/$id/stock': typeof AdminStoresIdStockRoute
  '/api/public/hooks/midtrans': typeof ApiPublicHooksMidtransRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/weekly-inquiry-summary': typeof ApiPublicHooksWeeklyInquirySummaryRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/accessories'
    | '/akun'
    | '/apparel'
    | '/auth'
    | '/carriers'
    | '/cart'
    | '/catalog'
    | '/footwear'
    | '/sitemap.xml'
    | '/stores'
    | '/tents'
    | '/wishlist'
    | '/$lang/checkout'
    | '/$lang/inquiry'
    | '/$lang/permintaan'
    | '/$lang/privacy'
    | '/$lang/stores'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/design'
    | '/admin/forgot-password'
    | '/admin/glossary'
    | '/admin/inquiries'
    | '/admin/languages'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/reset-password'
    | '/admin/restocks'
    | '/admin/shipping'
    | '/admin/size-guides'
    | '/admin/stores'
    | '/admin/vouchers'
    | '/akun/addresses'
    | '/akun/orders'
    | '/akun/profile'
    | '/c/$slug'
    | '/email/unsubscribe'
    | '/en/$'
    | '/$lang/'
    | '/admin/'
    | '/akun/'
    | '/en/'
    | '/$lang/inquiry/sent'
    | '/$lang/order/$id'
    | '/$lang/permintaan/terkirim'
    | '/$lang/products/$slug'
    | '/$lang/produk/$slug'
    | '/admin/customers/$email'
    | '/admin/inquiries/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/reports/regional'
    | '/admin/settings/notifications'
    | '/admin/settings/privacy'
    | '/lovable/email/suppression'
    | '/$lang/inquiry/'
    | '/$lang/permintaan/'
    | '/admin/products/'
    | '/admin/customers/$email/delete'
    | '/admin/customers/$email/export'
    | '/admin/products/$id/edit'
    | '/admin/products/$id/stock'
    | '/admin/stores/$id/stock'
    | '/api/public/hooks/midtrans'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/weekly-inquiry-summary'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/apparel'
    | '/auth'
    | '/carriers'
    | '/cart'
    | '/catalog'
    | '/footwear'
    | '/sitemap.xml'
    | '/stores'
    | '/tents'
    | '/wishlist'
    | '/$lang/checkout'
    | '/$lang/privacy'
    | '/$lang/stores'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/design'
    | '/admin/forgot-password'
    | '/admin/glossary'
    | '/admin/inquiries'
    | '/admin/languages'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/reset-password'
    | '/admin/restocks'
    | '/admin/shipping'
    | '/admin/size-guides'
    | '/admin/stores'
    | '/admin/vouchers'
    | '/akun/addresses'
    | '/akun/orders'
    | '/akun/profile'
    | '/c/$slug'
    | '/email/unsubscribe'
    | '/en/$'
    | '/$lang'
    | '/admin'
    | '/akun'
    | '/en'
    | '/$lang/inquiry/sent'
    | '/$lang/order/$id'
    | '/$lang/permintaan/terkirim'
    | '/$lang/products/$slug'
    | '/$lang/produk/$slug'
    | '/admin/customers/$email'
    | '/admin/inquiries/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/reports/regional'
    | '/admin/settings/notifications'
    | '/admin/settings/privacy'
    | '/lovable/email/suppression'
    | '/$lang/inquiry'
    | '/$lang/permintaan'
    | '/admin/products'
    | '/admin/customers/$email/delete'
    | '/admin/customers/$email/export'
    | '/admin/products/$id/edit'
    | '/admin/products/$id/stock'
    | '/admin/stores/$id/stock'
    | '/api/public/hooks/midtrans'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/weekly-inquiry-summary'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/accessories'
    | '/akun'
    | '/apparel'
    | '/auth'
    | '/carriers'
    | '/cart'
    | '/catalog'
    | '/footwear'
    | '/sitemap.xml'
    | '/stores'
    | '/tents'
    | '/wishlist'
    | '/$lang/checkout'
    | '/$lang/inquiry'
    | '/$lang/permintaan'
    | '/$lang/privacy'
    | '/$lang/stores'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/design'
    | '/admin/forgot-password'
    | '/admin/glossary'
    | '/admin/inquiries'
    | '/admin/languages'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/reset-password'
    | '/admin/restocks'
    | '/admin/shipping'
    | '/admin/size-guides'
    | '/admin/stores'
    | '/admin/vouchers'
    | '/akun/addresses'
    | '/akun/orders'
    | '/akun/profile'
    | '/c/$slug'
    | '/email/unsubscribe'
    | '/en/$'
    | '/$lang/'
    | '/admin/'
    | '/akun/'
    | '/en/'
    | '/$lang/inquiry/sent'
    | '/$lang/order/$id'
    | '/$lang/permintaan/terkirim'
    | '/$lang/products/$slug'
    | '/$lang/produk/$slug'
    | '/admin/customers/$email'
    | '/admin/inquiries/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/reports/regional'
    | '/admin/settings/notifications'
    | '/admin/settings/privacy'
    | '/lovable/email/suppression'
    | '/$lang/inquiry/'
    | '/$lang/permintaan/'
    | '/admin/products/'
    | '/admin/customers/$email/delete'
    | '/admin/customers/$email/export'
    | '/admin/products/$id/edit'
    | '/admin/products/$id/stock'
    | '/admin/stores/$id/stock'
    | '/api/public/hooks/midtrans'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/weekly-inquiry-summary'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AccessoriesRoute: typeof AccessoriesRoute
  AkunRoute: typeof AkunRouteWithChildren
  ApparelRoute: typeof ApparelRoute
  AuthRoute: typeof AuthRoute
  CarriersRoute: typeof CarriersRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  FootwearRoute: typeof FootwearRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRoute
  TentsRoute: typeof TentsRoute
  WishlistRoute: typeof WishlistRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAttributesRoute: typeof AdminAttributesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDesignRoute: typeof AdminDesignRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminGlossaryRoute: typeof AdminGlossaryRoute
  AdminInquiriesRoute: typeof AdminInquiriesRouteWithChildren
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminRestocksRoute: typeof AdminRestocksRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminSizeGuidesRoute: typeof AdminSizeGuidesRoute
  AdminStoresRoute: typeof AdminStoresRouteWithChildren
  AdminVouchersRoute: typeof AdminVouchersRoute
  CSlugRoute: typeof CSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EnSplatRoute: typeof EnSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminReportsRegionalRoute: typeof AdminReportsRegionalRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsPrivacyRoute: typeof AdminSettingsPrivacyRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
  AdminProductsIdStockRoute: typeof AdminProductsIdStockRoute
  ApiPublicHooksMidtransRoute: typeof ApiPublicHooksMidtransRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
  ApiPublicHooksWeeklyInquirySummaryRoute: typeof ApiPublicHooksWeeklyInquirySummaryRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tents': {
      id: '/tents'
      path: '/tents'
      fullPath: '/tents'
      preLoaderRoute: typeof TentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footwear': {
      id: '/footwear'
      path: '/footwear'
      fullPath: '/footwear'
      preLoaderRoute: typeof FootwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers': {
      id: '/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof CarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel': {
      id: '/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof ApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/': {
      id: '/akun/'
      path: '/'
      fullPath: '/akun/'
      preLoaderRoute: typeof AkunIndexRouteImport
      parentRoute: typeof AkunRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/en/$': {
      id: '/en/$'
      path: '/en/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/profile': {
      id: '/akun/profile'
      path: '/profile'
      fullPath: '/akun/profile'
      preLoaderRoute: typeof AkunProfileRouteImport
      parentRoute: typeof AkunRoute
    }
    '/akun/orders': {
      id: '/akun/orders'
      path: '/orders'
      fullPath: '/akun/orders'
      preLoaderRoute: typeof AkunOrdersRouteImport
      parentRoute: typeof AkunRoute
    }
    '/akun/addresses': {
      id: '/akun/addresses'
      path: '/addresses'
      fullPath: '/akun/addresses'
      preLoaderRoute: typeof AkunAddressesRouteImport
      parentRoute: typeof AkunRoute
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/admin/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/size-guides': {
      id: '/admin/size-guides'
      path: '/admin/size-guides'
      fullPath: '/admin/size-guides'
      preLoaderRoute: typeof AdminSizeGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/admin/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restocks': {
      id: '/admin/restocks'
      path: '/admin/restocks'
      fullPath: '/admin/restocks'
      preLoaderRoute: typeof AdminRestocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/admin/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/glossary': {
      id: '/admin/glossary'
      path: '/admin/glossary'
      fullPath: '/admin/glossary'
      preLoaderRoute: typeof AdminGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/design': {
      id: '/admin/design'
      path: '/admin/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AdminDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attributes': {
      id: '/admin/attributes'
      path: '/admin/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AdminAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/stores': {
      id: '/$lang/stores'
      path: '/stores'
      fullPath: '/$lang/stores'
      preLoaderRoute: typeof LangStoresRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/permintaan': {
      id: '/$lang/permintaan'
      path: '/permintaan'
      fullPath: '/$lang/permintaan'
      preLoaderRoute: typeof LangPermintaanRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/inquiry': {
      id: '/$lang/inquiry'
      path: '/inquiry'
      fullPath: '/$lang/inquiry'
      preLoaderRoute: typeof LangInquiryRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/checkout': {
      id: '/$lang/checkout'
      path: '/checkout'
      fullPath: '/$lang/checkout'
      preLoaderRoute: typeof LangCheckoutRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/permintaan/': {
      id: '/$lang/permintaan/'
      path: '/'
      fullPath: '/$lang/permintaan/'
      preLoaderRoute: typeof LangPermintaanIndexRouteImport
      parentRoute: typeof LangPermintaanRoute
    }
    '/$lang/inquiry/': {
      id: '/$lang/inquiry/'
      path: '/'
      fullPath: '/$lang/inquiry/'
      preLoaderRoute: typeof LangInquiryIndexRouteImport
      parentRoute: typeof LangInquiryRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/privacy': {
      id: '/admin/settings/privacy'
      path: '/admin/settings/privacy'
      fullPath: '/admin/settings/privacy'
      preLoaderRoute: typeof AdminSettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/admin/settings/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/regional': {
      id: '/admin/reports/regional'
      path: '/admin/reports/regional'
      fullPath: '/admin/reports/regional'
      preLoaderRoute: typeof AdminReportsRegionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/inquiries/$id': {
      id: '/admin/inquiries/$id'
      path: '/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminInquiriesIdRouteImport
      parentRoute: typeof AdminInquiriesRoute
    }
    '/admin/customers/$email': {
      id: '/admin/customers/$email'
      path: '/$email'
      fullPath: '/admin/customers/$email'
      preLoaderRoute: typeof AdminCustomersEmailRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/$lang/produk/$slug': {
      id: '/$lang/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/$lang/produk/$slug'
      preLoaderRoute: typeof LangProdukSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products/$slug': {
      id: '/$lang/products/$slug'
      path: '/products/$slug'
      fullPath: '/$lang/products/$slug'
      preLoaderRoute: typeof LangProductsSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/permintaan/terkirim': {
      id: '/$lang/permintaan/terkirim'
      path: '/terkirim'
      fullPath: '/$lang/permintaan/terkirim'
      preLoaderRoute: typeof LangPermintaanTerkirimRouteImport
      parentRoute: typeof LangPermintaanRoute
    }
    '/$lang/order/$id': {
      id: '/$lang/order/$id'
      path: '/order/$id'
      fullPath: '/$lang/order/$id'
      preLoaderRoute: typeof LangOrderIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/inquiry/sent': {
      id: '/$lang/inquiry/sent'
      path: '/sent'
      fullPath: '/$lang/inquiry/sent'
      preLoaderRoute: typeof LangInquirySentRouteImport
      parentRoute: typeof LangInquiryRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-inquiry-summary': {
      id: '/api/public/hooks/weekly-inquiry-summary'
      path: '/api/public/hooks/weekly-inquiry-summary'
      fullPath: '/api/public/hooks/weekly-inquiry-summary'
      preLoaderRoute: typeof ApiPublicHooksWeeklyInquirySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/midtrans': {
      id: '/api/public/hooks/midtrans'
      path: '/api/public/hooks/midtrans'
      fullPath: '/api/public/hooks/midtrans'
      preLoaderRoute: typeof ApiPublicHooksMidtransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores/$id/stock': {
      id: '/admin/stores/$id/stock'
      path: '/$id/stock'
      fullPath: '/admin/stores/$id/stock'
      preLoaderRoute: typeof AdminStoresIdStockRouteImport
      parentRoute: typeof AdminStoresRoute
    }
    '/admin/products/$id/stock': {
      id: '/admin/products/$id/stock'
      path: '/admin/products/$id/stock'
      fullPath: '/admin/products/$id/stock'
      preLoaderRoute: typeof AdminProductsIdStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/admin/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$email/export': {
      id: '/admin/customers/$email/export'
      path: '/export'
      fullPath: '/admin/customers/$email/export'
      preLoaderRoute: typeof AdminCustomersEmailExportRouteImport
      parentRoute: typeof AdminCustomersEmailRoute
    }
    '/admin/customers/$email/delete': {
      id: '/admin/customers/$email/delete'
      path: '/delete'
      fullPath: '/admin/customers/$email/delete'
      preLoaderRoute: typeof AdminCustomersEmailDeleteRouteImport
      parentRoute: typeof AdminCustomersEmailRoute
    }
  }
}

interface LangInquiryRouteChildren {
  LangInquirySentRoute: typeof LangInquirySentRoute
  LangInquiryIndexRoute: typeof LangInquiryIndexRoute
}

const LangInquiryRouteChildren: LangInquiryRouteChildren = {
  LangInquirySentRoute: LangInquirySentRoute,
  LangInquiryIndexRoute: LangInquiryIndexRoute,
}

const LangInquiryRouteWithChildren = LangInquiryRoute._addFileChildren(
  LangInquiryRouteChildren,
)

interface LangPermintaanRouteChildren {
  LangPermintaanTerkirimRoute: typeof LangPermintaanTerkirimRoute
  LangPermintaanIndexRoute: typeof LangPermintaanIndexRoute
}

const LangPermintaanRouteChildren: LangPermintaanRouteChildren = {
  LangPermintaanTerkirimRoute: LangPermintaanTerkirimRoute,
  LangPermintaanIndexRoute: LangPermintaanIndexRoute,
}

const LangPermintaanRouteWithChildren = LangPermintaanRoute._addFileChildren(
  LangPermintaanRouteChildren,
)

interface LangRouteChildren {
  LangCheckoutRoute: typeof LangCheckoutRoute
  LangInquiryRoute: typeof LangInquiryRouteWithChildren
  LangPermintaanRoute: typeof LangPermintaanRouteWithChildren
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangStoresRoute: typeof LangStoresRoute
  LangIndexRoute: typeof LangIndexRoute
  LangOrderIdRoute: typeof LangOrderIdRoute
  LangProductsSlugRoute: typeof LangProductsSlugRoute
  LangProdukSlugRoute: typeof LangProdukSlugRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangCheckoutRoute: LangCheckoutRoute,
  LangInquiryRoute: LangInquiryRouteWithChildren,
  LangPermintaanRoute: LangPermintaanRouteWithChildren,
  LangPrivacyRoute: LangPrivacyRoute,
  LangStoresRoute: LangStoresRoute,
  LangIndexRoute: LangIndexRoute,
  LangOrderIdRoute: LangOrderIdRoute,
  LangProductsSlugRoute: LangProductsSlugRoute,
  LangProdukSlugRoute: LangProdukSlugRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AkunRouteChildren {
  AkunAddressesRoute: typeof AkunAddressesRoute
  AkunOrdersRoute: typeof AkunOrdersRoute
  AkunProfileRoute: typeof AkunProfileRoute
  AkunIndexRoute: typeof AkunIndexRoute
}

const AkunRouteChildren: AkunRouteChildren = {
  AkunAddressesRoute: AkunAddressesRoute,
  AkunOrdersRoute: AkunOrdersRoute,
  AkunProfileRoute: AkunProfileRoute,
  AkunIndexRoute: AkunIndexRoute,
}

const AkunRouteWithChildren = AkunRoute._addFileChildren(AkunRouteChildren)

interface AdminCustomersEmailRouteChildren {
  AdminCustomersEmailDeleteRoute: typeof AdminCustomersEmailDeleteRoute
  AdminCustomersEmailExportRoute: typeof AdminCustomersEmailExportRoute
}

const AdminCustomersEmailRouteChildren: AdminCustomersEmailRouteChildren = {
  AdminCustomersEmailDeleteRoute: AdminCustomersEmailDeleteRoute,
  AdminCustomersEmailExportRoute: AdminCustomersEmailExportRoute,
}

const AdminCustomersEmailRouteWithChildren =
  AdminCustomersEmailRoute._addFileChildren(AdminCustomersEmailRouteChildren)

interface AdminCustomersRouteChildren {
  AdminCustomersEmailRoute: typeof AdminCustomersEmailRouteWithChildren
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersEmailRoute: AdminCustomersEmailRouteWithChildren,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminInquiriesRouteChildren {
  AdminInquiriesIdRoute: typeof AdminInquiriesIdRoute
}

const AdminInquiriesRouteChildren: AdminInquiriesRouteChildren = {
  AdminInquiriesIdRoute: AdminInquiriesIdRoute,
}

const AdminInquiriesRouteWithChildren = AdminInquiriesRoute._addFileChildren(
  AdminInquiriesRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminStoresRouteChildren {
  AdminStoresIdStockRoute: typeof AdminStoresIdStockRoute
}

const AdminStoresRouteChildren: AdminStoresRouteChildren = {
  AdminStoresIdStockRoute: AdminStoresIdStockRoute,
}

const AdminStoresRouteWithChildren = AdminStoresRoute._addFileChildren(
  AdminStoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AccessoriesRoute: AccessoriesRoute,
  AkunRoute: AkunRouteWithChildren,
  ApparelRoute: ApparelRoute,
  AuthRoute: AuthRoute,
  CarriersRoute: CarriersRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  FootwearRoute: FootwearRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRoute,
  TentsRoute: TentsRoute,
  WishlistRoute: WishlistRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAttributesRoute: AdminAttributesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDesignRoute: AdminDesignRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminGlossaryRoute: AdminGlossaryRoute,
  AdminInquiriesRoute: AdminInquiriesRouteWithChildren,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminRestocksRoute: AdminRestocksRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminSizeGuidesRoute: AdminSizeGuidesRoute,
  AdminStoresRoute: AdminStoresRouteWithChildren,
  AdminVouchersRoute: AdminVouchersRoute,
  CSlugRoute: CSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EnSplatRoute: EnSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  EnIndexRoute: EnIndexRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminReportsRegionalRoute: AdminReportsRegionalRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsPrivacyRoute: AdminSettingsPrivacyRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
  AdminProductsIdStockRoute: AdminProductsIdStockRoute,
  ApiPublicHooksMidtransRoute: ApiPublicHooksMidtransRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
  ApiPublicHooksWeeklyInquirySummaryRoute:
    ApiPublicHooksWeeklyInquirySummaryRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
